export type ButtonVariant = "outlined" | "filled" | "light" | "plain"
export type ProgressVariant = "bar" | "circle" | "half-circle"
export type RatingVariant = "heart" | "star"
export type Size = "sm" | "md" | "lg"
export type Position = "left" | "right" | "top" | "bottom" | "center"
export type Direction = "horizontal" | "vertical"
export type OnlineStatus = "online" | "offline"
