export type ButtonVariant = "outlined" | "filled" | "light" | "plain"
export type ProgressVariant = "bar" | "circle" | "half-circle"
export type Size = "sm" | "md" | "lg"
export type Position = "left" | "right" | "top" | "bottom"
export type LabelVariant = "title" | "subtitle" | "hint" | "icon"
